- ignore:
    name: Use camelCase
    within: Prelude
- ignore:
    name: Use camelCase
    within: GHC.IO.Exception
- ignore:
    name: Use foldl
    within: GHC.Read.Lex
- ignore:
    name: Use traverse
    within: GHC.Internal.Traversable
- ignore:
    name: Use sequenceA
    within: GHC.Internal.Traversable
- ignore:
    within: GHC.Boot.TH.Lib.Map
- ignore:
    within: GHC.Boot.TH.Ppr
- ignore:
    within: GHC.Boot.TH.PprLib
- ignore:
    within: GHC.Internal.TH.Lib
- ignore:
    within: GHC.Internal.TH.Lift
- ignore:
    within: GHC.Internal.TH.Syntax
- ignore:
    within: Language.Haskell.TH.Lib
- ignore:
    within: System.FilePath.Posix
- ignore:
    within: System.FilePath.Windows
