cabal-version: 3.8
name: aihc-template-haskell
version: 2.23.0.0
build-type: Simple
license: BSD-3-Clause
license-files:
  LICENSE

synopsis: API-compatible stand-in for template-haskell

library
  exposed-modules:
    Language.Haskell.TH
    Language.Haskell.TH.CodeDo
    Language.Haskell.TH.LanguageExtensions
    Language.Haskell.TH.Lib
    Language.Haskell.TH.Lib.Internal
    Language.Haskell.TH.Ppr
    Language.Haskell.TH.PprLib
    Language.Haskell.TH.Quote
    Language.Haskell.TH.Syntax

  other-modules:
    GHC.Boot.TH.Lib
    GHC.Boot.TH.Lib.Map
    GHC.Boot.TH.Lift
    GHC.Boot.TH.Ppr
    GHC.Boot.TH.PprLib
    GHC.Boot.TH.Quote
    GHC.Boot.TH.Syntax
    GHC.ForeignSrcLang.Type
    GHC.LanguageExtensions.Type
    GHC.Lexeme
    Text.PrettyPrint

  hs-source-dirs: src
  default-extensions: NoGeneralizedNewtypeDeriving
  build-depends:
    aihc-internal ==9.1204.0,
    base >=4.21 && <4.22

  default-language: GHC2021

test-suite public-api-fixture
  type: exitcode-stdio-1.0
  main-is: Main.hs
  hs-source-dirs: test
  build-depends:
    aihc-template-haskell,
    base >=4.21 && <4.22,

  default-language: GHC2021
